name: "GitHub ID Script"
description: "Add a user's GitHub ID to their is-a.dev pull request."
branding:
    icon: "user"
    color: "purple"
inputs:
    files:
        description: "Files that need to be updated"
        required: true
        default: "none"
    token:
        description: "Auth-Token for GH API"
        required: true
        default: "none"
runs:
    using: "node20"
    main: "index.js"
